security:
  # Password hasher
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # User providers
  providers:
    api:
      entity:
        class: App\Entity\User
        property: email
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/api
      stateless: true
      provider: api
      json_login:
        check_path: /api/login
        username_path: email
        password_path: password

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppCustomAuthenticator
      logout:
        path: app_logout
        # target: app_any_route
      # remember_me section removed (as you requested)

  # Access control
  access_control:
    - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_CHEF] }
    - { path: ^/commande, roles: [ROLE_USER] }
    # - { path: ^/profile, roles: ROLE_USER }
